//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPRG214.InlandMarinaLtd.App.Secure
{


    public partial class AllowLeasing
    {

        /// <summary>
        /// uxLeasing control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::CPRG214.InlandMarinaLtd.App.Controls.Leasing uxLeasing;
    }
}
